lib/connectx: Fix build for prefixed architectures
We need to take into consideration the __USER_LABEL_PREFIX__
for architectures that define it when creating symbol aliases.

Fixes the build for the Meta(metag) architecture

[...]
src/apps/sctp_test.c:801: undefined reference to `_sctp_connectx'
[...]

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>